# Generated by Django 5.2.3 on 2025-06-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('Customer_Id', models.CharField(max_length=20)),
                ('Customer_Name', models.CharField(max_length=255)),
                ('Customer_Phone', models.BigIntegerField()),
                ('Customer_Address', models.CharField(max_length=200)),
                ('Trip_Date', models.DateField(null=True)),
                ('Destination', models.CharField(max_length=200)),
                ('Driver_Name', models.CharField(max_length=100)),
                ('Vehicle_Id', models.CharField(max_length=20)),
                ('Vehicle_Registration_No', models.CharField(max_length=20, null=True)),
                ('Bill_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Quantity', models.FloatField(max_length=50, null=True)),
                ('Bill_Amount', models.FloatField(max_length=50, null=True)),
                ('Rate_Per_Bricks', models.FloatField(max_length=50, null=True)),
                ('Bill_Status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Id', models.CharField(max_length=20, unique=True)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Customer_Phone', models.BigIntegerField()),
                ('Customer_Address', models.CharField(max_length=200)),
                ('Paid_Amount', models.FloatField(blank=True, default=0)),
                ('Pending_Amount', models.FloatField(blank=True, default=0)),
                ('Bill_Amount', models.FloatField(blank=True, default=0)),
                ('Customer_Status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMaster',
            fields=[
                ('Payment_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Customer_Id', models.CharField(max_length=20, unique=True)),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Customer_Phone', models.BigIntegerField()),
                ('Customer_Address', models.CharField(max_length=200)),
                ('Payment_Date', models.DateField(auto_now_add=True)),
                ('Pay_Amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('Paid_Amount', models.FloatField(blank=True, default=0)),
                ('Pending_Amount', models.FloatField(blank=True, default=0)),
                ('Bill_Amount', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehicle_Id', models.CharField(max_length=20)),
                ('Vehicle_Registration_No', models.CharField(max_length=20, null=True)),
                ('Vehicle_Status', models.IntegerField(default=1)),
            ],
        ),
    ]
