# Generated by Django 5.2.3 on 2025-06-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmaster',
            name='Customer_Id',
            field=models.CharField(max_length=20),
        ),
    ]
