# Generated by Django 5.2.3 on 2025-06-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks_app', '0002_alter_paymentmaster_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmaster',
            name='Pay_Amount',
            field=models.FloatField(default=0.0),
        ),
    ]
