# Generated by Django 5.2.3 on 2025-06-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks_app', '0003_alter_paymentmaster_pay_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmaster',
            name='Bill_Status',
            field=models.IntegerField(default=1),
        ),
    ]
