# Generated by Django 5.2.3 on 2025-06-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bricks_app', '0004_paymentmaster_bill_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmaster',
            old_name='Bill_Status',
            new_name='Payment_Status',
        ),
    ]
